Write DropdownColorPicker test
paion-data/lexical pull request #1
Opened 2023-09-04 08:28 UTC by fannifanni

Changelog
---------

### Added

### Changed

### Deprecated

### Removed

### Fixed

### Security

Checklist
---------

- [ ] Test
- [ ] Self-review
- [ ] Documentation

2023-09-04 08:46 UTC, QubitPi requested changes

2023-09-04 08:46 UTC, QubitPi commented on .vscode/settings.json
> +    "editor.defaultFormatter": "vscode.typescript-language-features"
加这个是什么原因？

2023-09-05 01:01 UTC, QubitPi requested changes

2023-09-05 14:53 UTC, QubitPi requested changes

2023-09-05 14:53 UTC, QubitPi commented on .eslintrc.js
> +    ],
因为上面的 override 对所有的文件 `files: ['**/*.ts', '**/*.tsx']` 都用了 header，我在想这里是不是可以删掉，毕竟代码有重复

2023-09-07 01:43 UTC, Xxy1016 approved these changes

2023-09-07 06:36 UTC, QubitPi approved these changes

2023-09-07 06:37 UTC, merged